version: '3.8'

services:
  web:
    image: ruby:3.4.2
    command: bash -c "bundle install && bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    working_dir: /rails
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
