version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: new_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: ruby:3.4.2
    command: bash -c "bundle install && bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    working_dir: /rails
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/new_app_development
    depends_on:
      - db

volumes:
  postgres_data:
